=== dskoda1/471website/mywebroot/CS471/HW/F02/SOL/HW2/hw2f02.dtd
<!ELEMENT CourseOfferings (Department)*>
<!ELEMENT Department (#PCDATA|Course+) >
<!ELEMENT Course (Name, Instructor, Enrollment)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Instructor (#PCDATA)>
<!ELEMENT Enrollment (Max, Current)>
<!ELEMENT Max (#PCDATA)>
<!ELEMENT Current (#PCDATA)>

=== dskoda1/471website/mywebroot/CS471/HW/F02/SOL/HW2/hw2f02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE COfferings SYSTEM "HW2F02.dtd"> 

  <CourseOfferings> Here are the High School Course Offerings
    <Department>
      Math
      <Course>
	<Name>Calculus 1</Name>
	<Instructor>Prof Vector</Instructor>
	<Enrollment>
	  <Max>30</Max>
	  <Current>15</Current>
	</Enrollment>
      </Course>
      <Course>
	<Name>Linear Algebra</Name>
	<Instructor>Prof Algebra</Instructor>
	<Enrollment>
	  <Max>50</Max>
	  <Current>26</Current>
	</Enrollment>
      </Course>
    </Department>
    
    <Department>
      Computer Science
      <Course>
	<Name>Introduction to Programming</Name>
	<Instructor>Prof Java</Instructor>
	<Enrollment>
	  <Max>45</Max>
	  <Current>29</Current>
	</Enrollment>
      </Course>
    </Department>
    
  </CourseOfferings>
